spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate


  datasource:
    url: jdbc:mysql://localhost:3306/Zoo
    username: root
    password: Ziew9ohz
    driver-class-name: com.mysql.cj.jdbc.Driver